### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by Ravi9562** [laura-barluzzi/django-user-language-middleware#4]
Hi All,

I am getting below error
C:\Users\tejaw\PycharmProjects\CRM\venv\Scripts\python.exe C:/Users/tejaw/PycharmProjects/CRM/CRM_Integration.py
Traceback (most recent call last):
  File "C:/Users/tejaw/PycharmProjects/CRM/CRM_Integration.py", line 10, in <module>
    sugarcrm_conn = sugarcrm.Sugarcrm(url = sugarcrm_url, username = sugarcrm_user, password = sugarcrm_pass)
TypeError: object() takes no parameters

when I am trying to execute the below script which will help me authenticating to suite crm
import sugarcrm

sugarcrm_user = "xxx"
sugarcrm_pass = "xxxx"
sugarcrm_url = "xxxxxxxxxxxxxx"

sugarcrm_conn = None

try:
    sugarcrm_conn = sugarcrm.Sugarcrm(url = sugarcrm_url, username = sugarcrm_user, password = sugarcrm_pass)
except ValueError:
    print("can't connect to " + sugarcrm_url)
    exit(1)

It will be great if someone can give me some suggestions on how to clear this error.

**Comment by laura-barluzzi** [comment]
@Ravi9562 sorry for the late reply, but I believe this issue has nothing to do with the middleware. Why do you think they are linked? I don't see my middleware being mentioned in any of your errors.

**Comment by laura-barluzzi** [comment]
@Ravi9562 since I haven't heard back from you for over a year I assume this issue was not related to the middleware. Therefore, I close it. Thanks.
